config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'search/owner_search'
  get 'search/list_owner'

  get 'system/index', as: :system
  get 'system/info', as: :system_info
  patch 'system/update_marathon_config', as: :update_marathon_config
  patch 'system/update_mesos_config', as: :update_mesos_config
  patch 'system/update_domain_config', as: :update_domain_config
  patch 'system/update_swan_config', as: :update_swan_config
  patch 'system/update_registry_domain_config', as: :update_registry_domain_config
  patch 'system/update_graphna_config', as: :update_graphna_config

  get 'session/new', as: :new_session
  get 'session/particles'
  post 'session/create', as: :login
  delete 'session/destroy', as: :logout

  get 'settings/account', as: :setting
  get 'settings/group', as: :settings_group
  get 'settings/third', as: :settings_third

  post 'registry/notifications', as: :notifications
  get 'registry/token', as: :token

  get 'welcome/index', as: :dashboard

  resources :namespaces do
    resources :permissions

    resources :repositories do
      resources :repo_tags, only: [:show, :destroy] do
        member do
          put :vulnerabilities_check
          get :manifest_blob_page
        end
      end
    end

    resources :projects do
    end
  end

  resources :builds, only: [:create]
  resources :pods

  resources :audits, only: [:index]
  resources :versions
  resources :service_templates do
    resources :permissions do
    end
  end

  resources :groups do
    resources :users do
      member do
        delete :leave
        patch :update_quota_cpu
        patch :update_quota_mem
        patch :update_quota_disk
      end
    end

    member do
      patch :update_quota_cpu
      patch :update_quota_mem
      patch :update_quota_disk
    end

  end

  resources :users do
  end


  namespace :api do
    resources :nodes  do
    end

    resource :mesos, only: [:show], controller: :mesos, action: :index
  end


  resources :nodes do
    resources :containers, only: [:index, :show]  do
      member do
        patch :start
        patch :stop
        patch :kill
        patch :restart
        patch :pause
        patch :resume
        patch :remove

        get :stats
        get :stats_json
        get :logs
        get :console
      end
    end
    resources :images, only: [:index, :show] do
      member do
        patch :push
        patch :pull
        post  :tag
      end
    end
    resources :networks, only: [:index, :show] do
      member do
        delete :leave_from_network
      end
    end
    resources :volumes, only: [:index, :show]
  end

  put 'toggle_locale', controller: :application
  put 'set_main_content_width', controller: :application

  get 'welcome/index'
  get 'mesos/index', as: :mesos
  get 'marathon/index', as: :marathon
  get 'swan/index', as: :swan
  get 'graphna/index', as: :graphna_stats

  get 'mesos/ping', as: :ping_mesos
  get 'marathon/ping', as: :ping_marathon
  get 'graphna/ping', as: :ping_graphna_stats

  resources :services do
    resources :apps do
      member do
        put :run
        put :stop
        put :start
        put :restart
        put :change
        put :rollback
        put :scale
        put :swan_scale_up
        put :swan_scale_down

        get :backend_state
        get :detail
      end

      resources :versions
    end

    resources :permissions do
    end

    member do
      post :save_as_template
      put :favorite
      put :unfavorite
      post :download_compose
      get :compose_chose
    end
  end

  root to: "services#index"
end

app/controllers/containers_controller.rb
class ContainersController < NodesController
  ACTIONS = %w(start stop kill restart pause resume remove)
  before_action :set_container, except: :index
  before_action :set_breadcrumb

  def index
    @containers = Docker::Container.all(all: true)
  end

  def show
  end

  ACTIONS.each do |a|
    define_method a do
      @container.send a
    end
  end

  def stats
  end

  def stats_json
    render json: @container.stats
  end

  def logs
  end

  def console
  end

  private

  def set_container
      @container = Docker::Container.get params[:id]
  end

  def set_breadcrumb
    @breadcrumb_list = [OpenStruct.new(name_zh_cn: "全部节点", name_en: "Nodes", path: nodes_path)]

    if @node
      @breadcrumb_list.push OpenStruct.new(name_zh_cn: @node.display, name_en: @node.display, path: node_path(@node))
    end


    @breadcrumb_list.push OpenStruct.new(name_zh_cn: "全部容器", name_en: "Containers", path: node_containers_path(@node))

    if @container
      @breadcrumb_list.push OpenStruct.new(name_zh_cn: @container.info["Name"], name_en: @container.info["Name"], path: node_container_path(@node, id: @container.info["id"]))
    end
  end
end

app/helpers/containers_helper.rb
module ContainersHelper
  def parse_container(container)
    os = OpenStruct.new
    os.id = container.id
    os.state = container.info["State"]
    os.status = container.info["Status"]
    os.name = container.info["Names"].try(:first)
    os.command = container.info["Command"]
    os.image = container.info["Image"]
    os.ip = container.info["NetworkSettings"]["Networks"].try(:values).try(:first).try(:fetch,"IPAddress")
    os.ports = "" # (container.info["Ports"].try(:first) || {}).try(:fetch, "PublicPort")
    os
  end

  def container_actions
    [
      {action: "start", display: "启动", icon: "play", btn_suffix: "success"},
      {action: "stop", display: "停止", icon: "stop", btn_suffix: "danger"},
      {action: "kill", display: "杀死", icon: "", btn_suffix: "danger"},
      {action: "restart", display: "重启", icon: "play", btn_suffix: "primary"},
      {action: "pause", display: "暂停", icon: "pause", btn_suffix: "primary"},
      {action: "resume", display: "恢复", icon: "start", btn_suffix: "primary"},
      {action: "remove", display: "移除", icon: "trash", btn_suffix: "danger"},
    ]
  end
end

app/views/containers/_list.html.haml
= box_helper "warning" do
  = box_header_helper t("common.containers"), :server
  = box_body_helper do
    %table.table.table-bordered
      %thead
        %tr
          %th= t("container.state")
          %th= t("container.name")
          %th= t("container.image")
          %th= t("container.cmd")
          %th= t("container.ip")
          %th= t("container.port")
          %th 
    
      %tbody
        - node.containers.each do |c|
          - con = parse_container(c)
          %tr
            %td= container_state_helper con.state
            %td= link_to truncate(con.name, length: 30), node_container_path(node, id: con.id)
            %td= link_to truncate(con.image, length: 30), node_image_path(node, id: con.image)
            %td= con.command
            %td= con.ip
            %td= con.port
            %td= con.status

app/views/containers/index.html.haml
= render :partial => "containers/list", locals: { containers: @containers, node: @node }

app/views/containers/logs.html.haml
= box_helper "success" do
  = box_header_helper t("node.container_stdout_logs"), "info"
  = box_body_helper do
    .well= raw @container.logs(stdout: 1).gsub("\n", "<br>")

= box_helper "danger" do
  = box_header_helper t("node.container_stderr_logs"), "info"
  = box_body_helper do
    .well= @container.logs(stderr: 1).gsub("\n", "<br>")

app/views/containers/show.html.haml
= box_helper "success" do
  = box_header_helper t("container.operation"), "cogs"
  = box_body_helper do
    .btn-group{role: 'group', 'aria-label':'...'}
      - container_actions.each do |action|
        = link_to fa_icon(action[:icon]) + " " + action[:display], send("#{action[:action]}_node_container_path", @node, @container.id), method: :patch, class: "btn btn-#{action[:btn_suffix]} btn-lg", data: { confirm: t("common.confirm") }

= box_helper "success" do
  = box_header_helper t("container.status"), "cogs"
  = box_body_helper do
    = link_to fa_icon("area-chart", text: "指标"), stats_node_container_path(@node, @container.id)
    = link_to fa_icon("exclamation-circle", text: "日志"), logs_node_container_path(@node, @container.id)
    = link_to fa_icon("terminal", text: "控制台"), console_node_container_path(@node, @container.id)

    %table.table
      %tr
        %td 名称
        %td= @container.info["Name"]
      %tr
        %td 状态
        %td= @container.info["State"]["Status"]
      %tr
        %td 创建时间
        %td= @container.info["State"]["StartedAt"]


= box_helper "success" do
  = box_header_helper t("container.detail"), "cogs"
  = box_body_helper do
    %dl.dl-horizontal
      %dt= t("node.images")
      %dd= link_to @container.info["Image"], node_image_path(@node, id: @container.info["Image"])

      %dt= t("node.cmd")
      %dd= @container.info["Config"]["Cmd"].join

      %dt= t("node.envs")
      %dd
        %table.table
          %thead
            %th ENV
            %th VALUE
          %tbody
            - @container.info["Config"]["Env"].each do |env|
              %tr
                %td= env.split("=")[0]
                %td= env.split("=")[1]



= box_helper "success" do
  = box_header_helper t("container.volume"), "cogs"
  = box_body_helper do
    %table.table.table-stripped
      %thead
        %tr
          %td 主机地址
          %td 容器地址
      %tbody
        - (@container.info["HostConfig"]["Binds"] || []).each do |m|
          %tr
            - source, destination = m.split(":")[0], m.split(":")[1]
            %td= source
            %td= destination


= box_helper "success" do
  = box_header_helper t("container.networks"), "cogs"
  = box_body_helper do
    %table.table

app/views/containers/stats.html.haml
= content_for :custom_assets do
  = javascript_include_tag "container_stats"


%canvas#cpu-stats-chart
%canvas#memory-stats-chart
%canvas#network-stats-chart