config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'search/owner_search'
  get 'search/list_owner'

  get 'system/index', as: :system
  get 'system/info', as: :system_info
  patch 'system/update_marathon_config', as: :update_marathon_config
  patch 'system/update_mesos_config', as: :update_mesos_config
  patch 'system/update_domain_config', as: :update_domain_config
  patch 'system/update_swan_config', as: :update_swan_config
  patch 'system/update_registry_domain_config', as: :update_registry_domain_config
  patch 'system/update_graphna_config', as: :update_graphna_config

  get 'session/new', as: :new_session
  get 'session/particles'
  post 'session/create', as: :login
  delete 'session/destroy', as: :logout

  get 'settings/account', as: :setting
  get 'settings/group', as: :settings_group
  get 'settings/third', as: :settings_third

  post 'registry/notifications', as: :notifications
  get 'registry/token', as: :token

  get 'welcome/index', as: :dashboard

  resources :namespaces do
    resources :permissions

    resources :repositories do
      resources :repo_tags, only: [:show, :destroy] do
        member do
          put :vulnerabilities_check
          get :manifest_blob_page
        end
      end
    end

    resources :projects do
    end
  end

  resources :builds, only: [:create]
  resources :pods

  resources :audits, only: [:index]
  resources :versions
  resources :service_templates do
    resources :permissions do
    end
  end

  resources :groups do
    resources :users do
      member do
        delete :leave
        patch :update_quota_cpu
        patch :update_quota_mem
        patch :update_quota_disk
      end
    end

    member do
      patch :update_quota_cpu
      patch :update_quota_mem
      patch :update_quota_disk
    end

  end

  resources :users do
  end


  namespace :api do
    resources :nodes  do
    end

    resource :mesos, only: [:show], controller: :mesos, action: :index
  end


  resources :nodes do
    resources :containers, only: [:index, :show]  do
      member do
        patch :start
        patch :stop
        patch :kill
        patch :restart
        patch :pause
        patch :resume
        patch :remove

        get :stats
        get :stats_json
        get :logs
        get :console
      end
    end
    resources :images, only: [:index, :show] do
      member do
        patch :push
        patch :pull
        post  :tag
      end
    end
    resources :networks, only: [:index, :show] do
      member do
        delete :leave_from_network
      end
    end
    resources :volumes, only: [:index, :show]
  end

  put 'toggle_locale', controller: :application
  put 'set_main_content_width', controller: :application

  get 'welcome/index'
  get 'mesos/index', as: :mesos
  get 'marathon/index', as: :marathon
  get 'swan/index', as: :swan
  get 'graphna/index', as: :graphna_stats

  get 'mesos/ping', as: :ping_mesos
  get 'marathon/ping', as: :ping_marathon
  get 'graphna/ping', as: :ping_graphna_stats

  resources :services do
    resources :apps do
      member do
        put :run
        put :stop
        put :start
        put :restart
        put :change
        put :rollback
        put :scale
        put :swan_scale_up
        put :swan_scale_down

        get :backend_state
        get :detail
      end

      resources :versions
    end

    resources :permissions do
    end

    member do
      post :save_as_template
      put :favorite
      put :unfavorite
      post :download_compose
      get :compose_chose
    end
  end

  root to: "services#index"
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  name       :string
#  owner_id   :integer
#  desc       :text
#  icon       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#

class Group < ApplicationRecord
  include Accessor
  include FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  belongs_to :owner, class_name: "User", foreign_key: :owner_id
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :admin_users, proc { where("`group_users`.role = #{GroupUser.roles[:admin]}") }, through: :group_users, source: :user
  has_many :site_admins, proc { where("`group_users`.role = #{GroupUser.roles[:site_admin]}") }, through: :group_users, source: :user
  has_many :services, dependent: :destroy
  has_many :namespaces, dependent: :destroy
  has_many :service_templates, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true

  mount_uploader :icon, GroupIconUploader

  has_settings do |s|
    # mem 10G, disk 1024G
    s.key :quota, :defaults => { :cpu => 20, :mem => 10 * 1028 , :disk => 1024  }
  end

  def add_user!(user, role = :user)
    gu = self.group_users.find_or_create_by(user_id: user.id)
    if gu.role && (GroupUser.roles[role] > GroupUser.roles[gu.role] )
      return true
    end

    gu.send("#{role}!")
  end

  def conditional_services
    self.is_default? ? Service.all : self.services
  end

  def self.default_group
    Group.first
  end

  def display
    self.name
  end

  def default_icon
    :users
  end

  def is_default?
    Group.default_group == self
  end

  %w(cpu_used mem_used disk_used).each do |m|
    define_method m do
      self.conditional_services.reduce(0){|sum, s| sum += s.send(m); sum }
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :set_groups
  before_action :set_breadcrumb
  

  # GET /groups
  # GET /groups.json
  def index
    @group = current_user.groups.find_by(id: params[:group_id]) || @groups.first
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = current_user.groups.includes(:group_users).find params[:id]
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.owner = current_user

    respond_to do |format|
      if @group.save && @group.add_user!(current_user, :admin)
        audit(@group, "create", @group.name)
        format.html { redirect_to :back, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        audit(@group, "update", @group.name)
        format.html { redirect_to group_path(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  %w(cpu mem disk).each do |m|
    define_method "update_quota_#{m}" do
      @group = Group.find params[:id]
      @group.settings(:quota).send("#{m}=", params[:value])
      if @group.save
        audit(@group, "update", @group.name + " update #{m} to #{params[:value]}" )
        flash.notice = t("common.user_quota_update_success")
      else
        flash.alert = t("common.user_quota_update_fail")
      end

      redirect_to groups_path
    end
  end


  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    audit(@group, "destroy", @group.name )
    respond_to do |format|
      format.html { redirect_to groups_path, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  def set_groups
    @groups = current_user.groups.includes(:users).order(created_at: :asc).page params[:page]
  end

  def set_breadcrumb
    @breadcrumb_list = [OpenStruct.new(name_zh_cn: "全部组", name_en: "Groups", path: groups_path)]

    if @group
      @breadcrumb_list.push OpenStruct.new(name_zh_cn: @group.name, name_en: @group.name, path: group_path(@group))
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_params
    params.require(:group).permit(:name, :desc, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/details/_detail.html.haml
= box_helper "warning" do
  = box_header_helper t("common.detail_info")
  = box_body_helper do
    %dl.dl-horizontal
      %dt= t("common.name")
      %dd= group.name
      %dt= t("common.owner")
      %dd= group.owner.display
      %dt= t("common.created")
      %dd= l(group.created_at)
      %dt= t("common.user_count")
      %dd= group.users.length
      %dt= t("common.service_count")
      %dd= group.services.length

app/views/groups/details/_edit_form.html.haml
= box_helper "warning" do
  = simple_form_for(group, multiple: true, class: "form-horizontal") do |f|
    = box_header_helper t("common.detail_info") do
      .box-tools.pull-right
        = f.button :submit, t("common.update_group"), class: primary_btn_helper, data: { confirm: t("group.change_group_confirm") }

    = box_body_helper do
      .col-md-6
        = image_tag group.icon.small.try(:url) || "placeholder.png", width: 200, class: 'margin-bottom'
        %label.btn.btn-primary.btn-flat.btn-file{style: 'display: block; width: 200px;'}
          = f.input :icon, input_html: { style: "display: none;" }, label: fa_icon(:upload) + " " + t('common.upload_icon')

      .col-md-6
        = f.input :name, label: t("group.name")
        = f.input :desc, as: :text, label: t("group.desc")

app/views/groups/details/_quota.html.haml
= box_helper "success" do
  = box_header_helper t("common.group_quota") do
    .box-tools.pull-right

  = box_body_helper do
    .row
      .col-md-4.text-center.border-right
        = doughnut_chart chart_opts_helper(["CPU Used", "CPU Left"], "CPU Usage", group.cpu_used, group.settings(:quota).cpu.to_i - group.cpu_used, ["blue", "green"]), { height: 150 }
        %hr
        .row
          = form_tag update_quota_cpu_group_path(group), method: :patch do
            .col-sm-7
              .input-group
                = text_field_tag "value", group.settings(:quota).cpu, class: 'form-control', type: :number
                .input-group-addon CORE
            .col-sm-4.col-sm-offset-1.text-right
              = button_to "#", class: 'btn btn-default col-sm-8 pull-right btn-flat', type: :submit, data: { confirm: t("common.quota_change_confirm") } do
                = fa_icon :check

      .col-md-4.text-center
        = doughnut_chart chart_opts_helper(["Mem Used", "Mem Left"], "Mem Usage", group.mem_used, group.settings(:quota).mem.to_i - group.mem_used , ["yellow", "orange"]), { height: 150 }
        %hr
        .row
          = form_tag update_quota_mem_group_path(group), method: :patch do
            .col-sm-7
              .input-group
                = text_field_tag "value", group.settings(:quota).mem, class: 'form-control', type: :number
                .input-group-addon M
            .col-sm-4.col-sm-offset-1.text-right
              = button_to "#", class: 'btn btn-default col-sm-8 pull-right btn-flat', type: :submit, data: { confirm: t("common.quota_change_confirm") } do
                = fa_icon :check

      .col-md-4.text-center.border-left
        = doughnut_chart chart_opts_helper(["Disk Used", "Disk Left"], "Disk Usage", group.disk_used, group.settings(:quota).disk.to_i - group.disk_used), { height: 150 }
        %hr
        .row
          = form_tag update_quota_disk_group_path(group), method: :patch do
            .col-sm-7
              .input-group
                = text_field_tag "value", group.settings(:quota).disk, class: 'form-control', type: :number
                .input-group-addon G
            .col-sm-4.col-sm-offset-1.text-right
              = button_to "#", class: 'btn btn-default col-sm-8 pull-right btn-flat', type: :submit, data: { confirm: t("common.quota_change_confirm") } do
                = fa_icon :check

app/views/groups/details/_services.html.haml
= box_helper "danger" do
  = box_header_helper t("common.service")
  = box_body_helper do
    %table.table
      %thead
        %td= t("service.name")
        %td= t("service.desc")
        %td= t("common.application")

      - group.services.each do |service|
        %tr
          %td= link_to service.name, service_path(service)
          %td= service.desc.truncate(40)
          %td= service.apps.length

app/views/groups/details/_users.html.haml
= box_helper "warning" do
  = box_header_helper t("common.user") do
    .box-tools.pull-right
      -#= link_to fa_icon(:plus) + " " + t("group.enroll_new_user"), "", class: 'btn btn-success btn-sm btn-flat'
      = link_to fa_icon(:plus) + " " + t("group.new_group_user"), "#newUser", class: 'btn btn-primary btn-sm btn-flat', data: { toggle: 'modal' }
      = modal_dialog id: "newUser", header: { show_close: true, dismiss: 'modal', title: t('user.new_user') }, body:   { content: render(:partial => "users/form", locals: { group: @group, user: @group.users.new, siteadmin_require: false, groupadmin_require: true }) }, footer: { content: '' }

  = box_body_helper do
    %table.table
      %thead
        %th= t("user.role")
        %th= t("user.name")
        %th= t("user.email")
        %th= t("user.groups")
        %th

      - group.users.order_by_role.each do |user|
        - if user.persisted?
          %tr
            %td= t("user.#{group.group_users.where(user_id: user.id).first.role}")
            %td
              = image_tag user.icon.thumb.try(:url) || "user-profile.png", class: 'user-profile-thumb'
              = user.display
            %td= user.email
            %td
              - user.groups_without_default.order('created_at ASC').each do |g|
                = link_to g.name, group_path(g)
            %td
              = modal_dialog id: "editUser#{user.id}", header: { show_close: true, dismiss: 'modal', title: t('user.edit_user') }, body:   { content: render(:partial => "users/form", locals: { group: @group, user: user, siteadmin_require: false, groupadmin_require: true }) }, footer: { content: '' }
              = drop_down_menu :default, t("common.actions") do
                = drop_down_menu_item t("common.edit"), "#editUser#{user.id}", data: { toggle: 'modal' }
                = drop_down_menu_item t("common.remove"), leave_group_user_path(group, user), method: :delete, data: { confirm: t("common.remove") } unless group.is_default?

app/views/groups/details/_users_for_default_group.html.haml
= box_helper "warning" do
  = box_header_helper t("common.user") do
    .box-tools.pull-right
      = link_to fa_icon(:plus) + " " + t("group.new_group_user"), "#newUser", class: primary_btn_helper, data: { toggle: 'modal' }
      = modal_dialog id: "newUser", header: { show_close: true, dismiss: 'modal', title: t('user.new_user') }, body:   { content: render(:partial => "users/form", locals: { group: @group, user: @group.users.new, siteadmin_require: true, groupadmin_require: false }) }, footer: { content: '' }

  = box_body_helper do
    %table.table
      %thead
        %th= t("user.name")
        %th= t("user.email")
        %th= t("user.groups")
        %th= t("common.service")
        %th= t("common.quota")
        %th

      - group.users.order_by_role.each do |user|
        - if user.persisted?
          %tr
            %td
              = image_tag user.icon.thumb.try(:url) || "user-profile.png", class: 'user-profile-thumb', height: 25
              = user.display
              - if user.site_admin?
                = fa_icon('user-circle')

            %td= user.email
            %td
              - user.groups_without_default.order('created_at ASC').each do |g|
                = link_to g.name, group_path(g)
            %td= user.services.length
            %td
              %span
                = link_to update_quota_cpu_group_user_path(group,user), class: 'btn btn-default btn-sm btn-flat', method: :patch, data: {prompt: {title: t("common.update_quota_cpu"), name: "value", "value": user.settings(:quota).cpu} } do
                  = fa_icon(:edit, class: 'text-green')
                  %strong= user.settings(:quota).cpu
                  core
              %span
                = link_to update_quota_mem_group_user_path(group,user), class: 'btn btn-default btn-sm btn-flat', method: :patch, data: {prompt: {title: t("common.update_quota_mem"), name: "value", "value": user.settings(:quota).mem} } do
                  = fa_icon(:edit, class: 'text-green')
                  %strong= user.settings(:quota).mem
                  M
              %span
                = link_to update_quota_disk_group_user_path(group,user), class: 'btn btn-default btn-sm btn-flat', method: :patch, data: {prompt: {title: t("common.update_quota_disk"), name: "value", "value": user.settings(:quota).disk} } do
                  = fa_icon(:edit, class: 'text-green')
                  %strong= user.settings(:quota).disk
                  G
            %td
              = drop_down_menu :default, t("common.actions") do
                = drop_down_menu_item t("common.edit"), edit_user_path(user)
                = drop_down_menu_item t("common.remove"), leave_group_user_path(group, user), data: { confirm: t("common.remove") }