config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'search/owner_search'
  get 'search/list_owner'

  get 'system/index', as: :system
  get 'system/info', as: :system_info
  patch 'system/update_marathon_config', as: :update_marathon_config
  patch 'system/update_mesos_config', as: :update_mesos_config
  patch 'system/update_domain_config', as: :update_domain_config
  patch 'system/update_swan_config', as: :update_swan_config
  patch 'system/update_registry_domain_config', as: :update_registry_domain_config
  patch 'system/update_graphna_config', as: :update_graphna_config

  get 'session/new', as: :new_session
  get 'session/particles'
  post 'session/create', as: :login
  delete 'session/destroy', as: :logout

  get 'settings/account', as: :setting
  get 'settings/group', as: :settings_group
  get 'settings/third', as: :settings_third

  post 'registry/notifications', as: :notifications
  get 'registry/token', as: :token

  get 'welcome/index', as: :dashboard

  resources :namespaces do
    resources :permissions

    resources :repositories do
      resources :repo_tags, only: [:show, :destroy] do
        member do
          put :vulnerabilities_check
          get :manifest_blob_page
        end
      end
    end

    resources :projects do
    end
  end

  resources :builds, only: [:create]
  resources :pods

  resources :audits, only: [:index]
  resources :versions
  resources :service_templates do
    resources :permissions do
    end
  end

  resources :groups do
    resources :users do
      member do
        delete :leave
        patch :update_quota_cpu
        patch :update_quota_mem
        patch :update_quota_disk
      end
    end

    member do
      patch :update_quota_cpu
      patch :update_quota_mem
      patch :update_quota_disk
    end

  end

  resources :users do
  end


  namespace :api do
    resources :nodes  do
    end

    resource :mesos, only: [:show], controller: :mesos, action: :index
  end


  resources :nodes do
    resources :containers, only: [:index, :show]  do
      member do
        patch :start
        patch :stop
        patch :kill
        patch :restart
        patch :pause
        patch :resume
        patch :remove

        get :stats
        get :stats_json
        get :logs
        get :console
      end
    end
    resources :images, only: [:index, :show] do
      member do
        patch :push
        patch :pull
        post  :tag
      end
    end
    resources :networks, only: [:index, :show] do
      member do
        delete :leave_from_network
      end
    end
    resources :volumes, only: [:index, :show]
  end

  put 'toggle_locale', controller: :application
  put 'set_main_content_width', controller: :application

  get 'welcome/index'
  get 'mesos/index', as: :mesos
  get 'marathon/index', as: :marathon
  get 'swan/index', as: :swan
  get 'graphna/index', as: :graphna_stats

  get 'mesos/ping', as: :ping_mesos
  get 'marathon/ping', as: :ping_marathon
  get 'graphna/ping', as: :ping_graphna_stats

  resources :services do
    resources :apps do
      member do
        put :run
        put :stop
        put :start
        put :restart
        put :change
        put :rollback
        put :scale
        put :swan_scale_up
        put :swan_scale_down

        get :backend_state
        get :detail
      end

      resources :versions
    end

    resources :permissions do
    end

    member do
      post :save_as_template
      put :favorite
      put :unfavorite
      post :download_compose
      get :compose_chose
    end
  end

  root to: "services#index"
end

app/views/apps/_app_item.html.haml
%td
  %strong
    = link_to app.name, service_path(service, app_id: app.id)
%td
  %span.text-muted
    = t('common.image')
    \:
  = app.image
%td
  %span.text-muted
    = t('common.version')
    \:
  %strong.text-primary= "version-1.10"
%td.text-center{class: "app_state app_state_#{app.id}", data: { 'app-state-path': backend_state_service_app_path(service, app)}}
  = fa_icon("cog", class: "fa-spin fa-2x")

%td.text-center
  = app.instances
  = t('common.containers')
%td.text-center
  = drop_down_menu :default, t("common.actions") do
    = drop_down_menu_item t("common.edit"), service_app_path(service, app), data: { turbolinks: false }
    = drop_down_menu_item t("common.copy"), new_service_app_path(service, app_id: app.id), data: { turbolinks: false }
    = drop_down_menu_item_sepeartor
    = drop_down_menu_item t("common.remove"), service_app_path(service, app), method: :delete

app/views/apps/_backend_state.html.haml
- if marathon_app
  - if marathon_app.info[:tasksRunning]
    %span.text-muted= t("app.running")
    %strong= marathon_app.info[:tasksRunning]

  - if marathon_app.info[:tasksStaged]
    %span.text-muted= t("app.staged")
    %strong= marathon_app.info[:tasksStaged]

  - if marathon_app.info[:tasksHealthy]
    %span.text-muted= t("app.healthy")
    %strong= marathon_app.info[:tasksHealthy]

  - if marathon_app.info[:tasksUnhealthy]
    %span.text-muted= t("app.unhealthy")
    %strong= marathon_app.info[:tasksUnhealthy]


  %br
    = link_to t("app.scale"), scale_service_app_path(service, app), method: :put, remote: :true, data: { prompt: {"title": t("app.scale_app"), "name": "scale_size", "value": 1, "type": "input"} }, class: "#{policy(service).update? ? '' : 'disabled'}"
    = link_to t("app.stop"), stop_service_app_path(service, app), method: :put, remote: :true, data: { confirm: t("app.stop_app_confirm")}, class: "#{policy(service).update? ? '' : 'disabled'}"
    = link_to t("app.restart"), restart_service_app_path(service, app), method: :put, remote: :true, data: { confirm: t("app.restart_confirm") }, class: "#{policy(service).update? ? '' : 'disabled'}"
    - if app.versions.length > 1
      = link_to t("app.update_version"), change_service_app_path(service, app), method: :put, remote: true, data: { prompt: {title: t("app.update_version"), name: "version_id", value: (app.versions - [app.current_version]).reduce({}){|r, v| r[v.name] = v.id; r}.to_query, type: "select" } }, class: "#{policy(service).update? ? '' : 'disabled'}"

- else
  = link_to fa_icon(:play, class: "fa-2x"), run_service_app_path(service, app), method: :put, remote: true, data: { prompt: {"title": t("app.start_app"), "name": "start_size", "value": 1, "type": "input"} }, class: "#{policy(service).update? ? '' : 'disabled'}"

app/views/apps/_detail.html.haml
= render :partial => "apps/details/info", locals: { app: app }
= render :partial => "apps/details/tasks", locals: { app: app, marathon_app: app.marathon_app}
= render :partial => "apps/details/versions", locals: {app: app, versions: app.versions, service: service }
= render :partial => "apps/details/audits", locals: { audits: app.audits }

app/views/apps/_form.html.erb
<%= content_for :custom_assets do %>
  <%= javascript_include_tag :angularjs %>
<% end %>

<%= javascript_tag do %>
  var appObj = JSON.parse('<%= @app.attributes.except(*App::PROTECTED_ATTRIBUTES).to_json.html_safe%>');

  var appLinks = JSON.parse('<%= @app_links.map{|al| al.attributes.slice("output_app_id", "alias", "id")}.to_json.html_safe%>');
  appLinks.forEach(function(link){ link['_destroy'] = 0;})
  appObj.app_links = appLinks;

  var appsUnderService = JSON.parse('<%= Hash[@service.apps.select(&:persisted?).map{|a| [a.name, a.id] }].to_json.html_safe%>');
  var webservicesUnderApp = JSON.parse('<%= Hash[@service.apps.select(&:persisted?).map{|a| [a.id, Hash[a.portmappings.pluck("name", "servicePort")]] }].to_json.html_safe%>');
  $('#appTab a:first').tab('show');

  var locale = '<%= session[:locale] %>';
  <% if @persisted %>
    var appPersisted = true;
    var postPath = "/services/" +  "<%= @service.id %>" + "/apps/" + <%= @app.id %>;
    var httpMethod = "put";
  <% else %>
    var appPersisted = false;
    var postPath = "/services/" +  "<%= @service.id %>" + "/apps";
    var httpMethod = "post";
  <% end %>
<% end %>

<div ng-app="app">
  <div class='row' ng-controller='AppController'>
    <form class="form-horizontal" name="appForm" ng-submit="submit()">
      <div class='box'>
        <div class="box-header with-border">
          <h4 class="box-title"><%= fa_icon(:copy) %> <%= t("app.app_form_title") %> </h4>
          <div class="box-tools pull-right">
            <button type="submit" class="<%= primary_btn_helper %>"><%= t('common.save') %></button>
            <%= link_to t("common.cancel"), services_path, class: 'btn btn-sm btn-success btn-flat' %>
          </div>
        </div>
        <div class="box-body">
          <div class="form_section col-md-12">
            <div class="form-group" ng-class="{ 'has-error' : appForm.name.$invalid && (appForm.name.$dirty || submitted)}" >
              <label for="name" class="col-sm-2 control-label"><%= t("app.name") %></label>
              <div class="col-sm-10">
                <input type="input" name="name" class="form-control" id="name" ng-model="app.name" ng-required="true" ng-disabled="appPersisted">
                <p ng-show="appForm.name.$invalid && (appForm.name.$dirty || submitted)" class="help-block">required.</p>
              </div>
            </div>

            <div class="form-group" ng-class="{ 'has-error' : appForm.desc.$invalid && (appForm.desc.$dirty || submitted)}" >
              <label for="desc" class="col-sm-2 control-label"><%= t("app.desc") %></label>
              <div class="col-sm-10">
                <input type="input" name="desc" class="form-control" id="desc" ng-model="app.desc" ng-required="true" >
                <p ng-show="appForm.desc.$invalid && (appForm.desc.$dirty || submitted)" class="help-block">required</p>
              </div>
            </div>


            <div class="form-group" ng-class="{ 'has-error' : appForm.image.$invalid && (appForm.image.$dirty || submitted)}" >
              <label for="image" class="col-sm-2 control-label"><%= t("app.select_image") %></label>
              <div class="col-sm-10">
                <input type="input" name="image" class="form-control" id="image" ng-model="app.image" ng-required='true'>
                <p ng-show="appForm.image.$invalid && (appForm.image.$dirty || submitted)" class="help-block">required</p>
              </div>
            </div>

            <div class="form-group" ng-class="{ 'has-error' : appForm.cpu.$invalid && (appForm.cpu.$dirty || submitted)}" >
              <label for="cpu" class="col-sm-2 control-label"><%= t("active_record.common.cpu") %></label>
              <div class="col-sm-10">
                <input type="float" name="cpu" class="form-control" id="cpu" ng-model="app.cpu" ng-required="true">
                <p ng-show="appForm.cpu.$invalid && (appForm.cpu.$dirty || submitted)" class="help-block">required</p>
              </div>
            </div>
            
            <div class="form-group" ng-class="{ 'has-error' : appForm.mem.$invalid && (appForm.mem.$dirty || submitted)}" >
              <label for="mem" class="col-sm-2 control-label"><%= t("active_record.common.mem") %></label>
              <div class="col-sm-10">
                <input type="number" name="mem" class="form-control" id="mem" ng-model="app.mem" ng-required="true">
                <p ng-show="appForm.mem.$invalid && (appForm.mem.$dirty || submitted)" class="help-block">required</p>
              </div>
            </div>

            <div class="form-group" ng-class="{ 'has-error' : appForm.disk.$invalid && (appForm.disk.$dirty || submitted)}" >
              <label for="disk" class="col-sm-2 control-label"><%= t("active_record.common.disk") %></label>
              <div class="col-sm-10">
                <input type="number" name="disk" class="form-control" id="disk" ng-model="app.disk" ng-required="true">
                <p ng-show="appForm.disk.$invalid && (appForm.disk.$dirty || submitted)" class="help-block">required</p>
              </div>
            </div>
            

            <!--
            <div class="form-group" ng-class="{ 'has-error' : appForm.network.$invalid && (appForm.network.$dirty || submitted)}" >
              <label for="network" class="col-sm-2 control-label"><%= t("app.network") %></label>
              <div class="col-sm-10">
                <label><input value="bridge" type="radio" name="network" ng-model="app.network" /><%= t("app.bridge") %></label>
                <label><input value="host" type="radio" name="network" ng-model="app.network" /><%= t("app.host") %></label>
              </div>
            </div>
            -->

            <div class="form-group" ng-class="{ 'has-error' : portMappingHasError() }" ng-show="app.network == 'bridge' || app.network == 'host'">
              <label for="portmappings" class="col-sm-2 control-label"><%= t("app.portmappings") %></label>
              <div class="col-sm-10">
                <table class="table table-bordered col-md-6 col-sm-12">
                  <tr>
                    <th><%= t('app.port_name') %></td>
                    <th><%= t('app.container_port') %></td>
                    <th><%= t('app.service_port') %></td>
                    <th><%= t('app.proto') %></td>
                    <th></td>
                  </tr>
                  <tbody>
                    <tr  ng-repeat="portmapping in app.portmappings">
                      <td>
                        <input type="input" class="form-control" name="portmapping_{{$index}}_name" ng-model="portmapping.name" ng-required=true>
                        <p ng-show="appForm.portmapping_{{$index}}_name.$invalid && (appForm.portmapping_{{$index}}_name.$dirty || submitted)" class="help-block">required</p>
                      </td>
                      <td>
                        <input type="number" class="form-control"  name="portmapping_{{$index}}_containerPort"  ng-model="portmapping.containerPort" ng-required=true>
                        <p ng-show="appForm.portmapping_{{$index}}_containerPort.$invalid && (appForm.portmapping_{{$index}}_containerPort.$dirty || submitted)" class="help-block">required</p>
                      </td>
                      <td>
                        <input type="number" class="form-control" name="portmapping_{{$index}}_servicePort" ng-model="portmapping.servicePort" ng-required=true>
                        <p ng-show="appForm.portmapping_{{$index}}_servicePort.$invalid && (appForm.portmapping_{{$index}}_servicePort.$dirty || submitted)" class="help-block">required</p>
                      </td>
                      <td>
                        <select class='form-control app-select' ng-model='portmapping.proto' ng-required=true>
                          <option value="tcp"> TCP </option>
                          <option value="udp"> UDP </option>
                        </select>
                      </td>
                      <td><a class="btn btn-default btn-sm" ng-click="removePortmapping($index)" ng-if="$index != 0"><%= fa_icon(:minus)%> </a></td>
                    </tr>
                    <tr>
                      <td colspan=5><a class="btn btn-default btn-sm" ng-click="morePortmapping()"><%= fa_icon(:plus)%> <%= t('app.add_portmapping') %> </a></td>
                    </tr>
                  </tbody>
                </table>
                <p ng-show="appForm.portmappings.$invalid && (appForm.portmappings.$dirty || submitted)" class="help-block">You name is required.</p>
              </div>
            </div>

            <div class="form-group" ng-class="{ 'has-error' : false }" ng-show="Object.keys(appsUnderService).length != 0">
              <label for="app_links" class="col-sm-2 control-label"><%= t("app.app_links") %></label>
              <div class="col-sm-10">
                <table class="table table-bordered col-md-6 col-sm-12">
                  <tr>
                    <th><%= t('app.link_alias') %></td>
                    <th><%= t('app.link_output') %></td>
                    <th><%= t('app.link_output_service') %></td>
                    <th><%= t('app.accessible_through') %></td>
                    <th></td>
                  </tr>
                  <tbody>
                    <tr ng-repeat="link in app.app_links | filter: {_destroy: 0}">
                      <td>
                        <input type="input" class="form-control" name="appForm.app_links_{{$index}}_alias" ng-model="link.alias" ng-required=true>
                        <p ng-show="appForm.app_links_{{$index}}_alias.$invalid && (appForm.app_links_{{$index}}_alias.$dirty || submitted)" class="help-block">required</p>
                      </td>
                      <td>
                        <select class='form-control app-select' ng-model='link.output_app_id' required="required" ng-options="v as k for (k, v) in appsUnderService" > </select>
                      </td>
                      <td>
                        <select class='form-control app-select' ng-model='link.output_service' required="required" ng-options="name as name for (name, serviceName) in webservicesUnderApp[link.output_app_id]" > </select>
                      </td>
                      <td>
                        {{link.alias}}:{{webservicesUnderApp[link.output_app_id][link.output_service]}}
                      </td>
                      <td><a class="btn btn-default btn-sm" ng-click="removeLink($index)"><%= fa_icon(:minus)%> </a></td>
                    </tr>
                    <tr>
                      <td colspan=5><a class="btn btn-default btn-sm" ng-click="moreLink()"><%= fa_icon(:plus)%> <%= t('app.add_link') %> </a></td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

          </div>

          <hr>

          <div class='form_section col-md-12'>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist" id='appTab'>
              <li role="presentation" class="active"><a href="#command" aria-controls="command" role="tab" data-toggle="tab"><%= t('service.command') %></a></li>
              <li role="presentation"><a href="#volumes" aria-controls="volumes" role="tab" data-toggle="tab"><%= t('service.volumes') %></a></li>
              <li role="presentation"><a href="#uri" aria-controls="uri" role="tab" data-toggle="tab"><%= t('service.uri') %></a></li>
              <li role="presentation"><a href="#labels" aria-controls="labels" role="tab" data-toggle="tab"><%= t('service.labels') %></a></li>
              <li role="presentation"><a href="#health_check" aria-controls="health_check" role="tab" data-toggle="tab"><%= t('service.health_check') %></a></li>
              <li role="presentation"><a href="#scheduling" aria-controls="scheduling" role="tab" data-toggle="tab"><%= t('service.scheduling') %></a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
              <div role="tabpanel" class="tab-pane active" id="command">
                <%= render partial: 'apps/form/command' %>
              </div>

              <div role="tabpanel" class="tab-pane" id="volumes">
                <%= render partial: 'apps/form/volumes' %>
              </div>

              <div role="tabpanel" class="tab-pane" id="uri">
                <%= render partial: 'apps/form/uri' %>
              </div>

              <div role="tabpanel" class="tab-pane" id="labels">
                <%= render partial: 'apps/form/labels' %>
              </div>

              <div role="tabpanel" class="tab-pane" id="health_check">
                <%= render partial: 'apps/form/health_check' %>
              </div>

              <div role="tabpanel" class="tab-pane" id="scheduling">
                <%= render partial: 'apps/form/scheduling' %>
              </div>
            </div>
          </div>

          <div class="form-group text-center">
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

app/views/apps/_marathon_app_state.html.haml
- if marathon_app
  - if marathon_app.info[:tasksRunning]
    %span.text-muted= t("app.running")
    %strong= marathon_app.info[:tasksRunning]

  - if marathon_app.info[:tasksStaged]
    %span.text-muted= t("app.staged")
    %strong= marathon_app.info[:tasksStaged]

  - if marathon_app.info[:tasksHealthy]
    %span.text-muted= t("app.healthy")
    %strong= marathon_app.info[:tasksHealthy]

  - if marathon_app.info[:tasksUnhealthy]
    %span.text-muted= t("app.unhealthy")
    %strong= marathon_app.info[:tasksUnhealthy]

  %br
    = link_to t("app.scale"), scale_service_app_path(service, app), method: :put, remote: :true, data: { prompt: {"title": t("app.scale_app"), "name": "scale_size", "value": 1, "type": "input"} }, class: "#{policy(service).update? ? '' : 'disabled'}"
    = link_to t("app.stop"), stop_service_app_path(service, app), method: :put, remote: :true, data: { confirm: t("app.stop_app_confirm")}, class: "#{policy(service).update? ? '' : 'disabled'}"
    = link_to t("app.restart"), restart_service_app_path(service, app), method: :put, remote: :true, data: { confirm: t("app.restart_confirm") }, class: "#{policy(service).update? ? '' : 'disabled'}"
    - if app.versions.length > 1
      = link_to t("app.update_version"), change_service_app_path(service, app), method: :put, remote: true, data: { prompt: {title: t("app.update_version"), name: "version_id", value: (app.versions - [app.current_version]).reduce({}){|r, v| r[v.name] = v.id; r}.to_query, type: "select" } }, class: "#{policy(service).update? ? '' : 'disabled'}"

- else
  = link_to fa_icon(:play, class: "fa-2x"), run_service_app_path(service, app), method: :put, remote: true, data: { prompt: {"title": t("app.start_app"), "name": "start_size", "value": 1, "type": "input"} }, class: "#{policy(service).update? ? '' : 'disabled'}"

app/views/apps/_swan_app_state.html.haml
- if swan_app
  - if swan_app.info[:instances]
    %span.text-muted= t("app.running")
    %strong= swan_app.info[:instances]

  - if swan_app.info[:state]
    %span.text-muted= t("app.state")
    %strong= swan_app.info[:state]

  %br
    = link_to t("app.scale_up"), swan_scale_up_service_app_path(service, app), method: :put, remote: :true, data: { prompt: {"title": t("app.scale_up_app"), "name": "scale_size", "value": swan_app.info[:instances], "type": "input"} }, class: "#{policy(service).update? ? '' : 'disabled'}"
    = link_to t("app.scale_down"), swan_scale_down_service_app_path(service, app), method: :put, remote: :true, data: { prompt: {"title": t("app.scale_up_app"), "name": "scale_size", "value": swan_app.info[:instances], "type": "input"} }, class: "#{policy(service).update? ? '' : 'disabled'}"
    = link_to t("app.stop"), stop_service_app_path(service, app), method: :put, remote: :true, data: { confirm: t("app.stop_app_confirm")}, class: "#{policy(service).update? ? '' : 'disabled'}"
    - if app.versions.length > 1
      = link_to t("app.update_version"), change_service_app_path(service, app), method: :put, remote: true, data: { prompt: {title: t("app.update_version"), name: "version_id", value: (app.versions - [app.current_version]).reduce({}){|r, v| r[v.name] = v.id; r}.to_query, type: "select" } }, class: "#{policy(service).update? ? '' : 'disabled'}"

- else
  = link_to fa_icon(:play, class: "fa-2x"), run_service_app_path(service, app), method: :put, remote: true, data: {confirm: t('common.confirm') }, class: "#{policy(service).update? ? '' : 'disabled'}"

app/views/apps/backend_state.html.haml
- case Site.default.backend_option
- when "marathon"
  = render :partial => "marathon_app_state", locals: { app: @app, service: @service, marathon_app: @app.marathon_app }
- when "swan"
  = render :partial => "swan_app_state", locals: { app: @app, service: @service, swan_app: @app.swan_app }

app/views/apps/detail.html.haml
.row
  .col-md-4.col-lg-2
    = render :partial => "services/service_left", locals: { service: @service, current_app: @app }
  .col-md-8.col-lg-10#app_detail
    = render :partial => "apps/detail", locals: { app: @app || @service.apps.first, service: @service }

app/views/apps/edit.html.haml
= render :partial => "form"

app/views/apps/index.html.haml
= render :partial => "apps/list", locals: { apps: @apps }

app/views/apps/restart.js.erb
<% if Site.default.backend_option == "marathon" %>
  $(".app_state_<%= @app.id %>").html("<%= escape_javascript(render(partial: 'marathon_app_state', locals: {app: @app, marathon_app: @app.marathon_app, service: @service })) %>");
<% end %>

<% if Site.default.backend_option == "swan" %>
  $(".app_state_<%= @app.id %>").html("<%= escape_javascript(render(partial: 'swan_app_state', locals: {app: @app, swan_app: @app.swan_app, service: @service })) %>");
<% end %>

app/views/apps/rollback.js.erb
$(".app_state_<%= @app.id %>").html("<%= escape_javascript(render(partial: 'backend_state', locals: {app: @app, marathon_app: @marathon_app, service: @service })) %>");

app/views/apps/scale.js.erb
<% if Site.default.backend_option == "marathon" %>
  $(".app_state_<%= @app.id %>").html("<%= escape_javascript(render(partial: 'marathon_app_state', locals: {app: @app, marathon_app: @app.marathon_app, service: @service })) %>");
<% end %>

<% if Site.default.backend_option == "swan" %>
  $(".app_state_<%= @app.id %>").html("<%= escape_javascript(render(partial: 'swan_app_state', locals: {app: @app, swan_app: @app.swan_app, service: @service })) %>");
<% end %>

app/views/apps/stop.js.erb
<% if Site.default.backend_option == "marathon" %>
  $(".app_state_<%= @app.id %>").html("<%= escape_javascript(render(partial: 'marathon_app_state', locals: {app: @app, marathon_app: @app.marathon_app, service: @service })) %>");
<% end %>

<% if Site.default.backend_option == "swan" %>
  $(".app_state_<%= @app.id %>").html("<%= escape_javascript(render(partial: 'swan_app_state', locals: {app: @app, swan_app: @app.swan_app, service: @service })) %>");
<% end %>